module.exports = {
  // 404 error codes
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  UNKNOWN_ENDPOINT: "UNKNOWN_ENDPOINT",

  // 400 error codes
  INVALID_REQUEST_PARAMETERS: "INVALID_REQUEST_PARAMETERS",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_JSON_FORMAT: "INVALID_JSON_FORMAT",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",

  // 401 error codes
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  MISSING_AUTH_HEADER: "MISSING_AUTH_HEADER",
  MALFORMED_TOKEN: "MALFORMED_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",

  // 403 error codes
  ACCESS_DENIED: "ACCESS_DENIED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  USER_NOT_VERIFIED: "USER_NOT_VERIFIED",

  // 500 error codes
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  THIRD_PARTY_API_FAILURE: "THIRD_PARTY_API_FAILURE",

  // 409 error codes
  EXISTING_USER_EMAIL: "EXISTING_USER_EMAIL",
  CONFLICT_ERROR_CODE: "CONFLICT_ERROR_CODE",
  EXIST_FACILITIES: "EXIST_FACILITIES",
  EXIST_MEDIAS: "EXIST_MEDIAS",
};
