name: Authentication Service

on:
  push:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy to server
      run: |
        ssh hngx@104.248.143.148 'cd authentication_service && git pull origin dev && npm install && pm2 restart index.js'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

